#!/bin/bash

# Simple command-line utility for studying flashcards

usage() { echo "Usage: bashcards [-h|-H] DECKFILE"; }

REVERSE='FALSE' # Variable determines side display order

while getopts "hHrR" options; do
	case ${options} in
		h|H)
			usage
			exit
			;;
		r|R)
			REVERSE='TRUE'
			shift "$((OPTIND-1))"
			;;
	esac
done




INPUT=$1 # Input csv deck file from which cards are read


# Display utility title
printf "* BASHCARDS *\n"
printf "_____________\n\n"

# Display name of deck
printf "Studying deck \"$(basename -s .csv "$INPUT")\"\n\n\n"


# If reverse mode is on, use the second field as the front of card
if [[ $REVERSE == 'TRUE' ]]; then
	FRONTFIELD="2"
	BACKFIELD="1"
else
	FRONTFIELD="1"
	BACKFIELD="2"
fi	


while read -r line; do
	# Read front and back of each card
	FRONT="$(cut -d',' -f$FRONTFIELD <(echo $line))"
	BACK="$(cut -d',' -f$BACKFIELD <(echo $line))"

	# Prompt user with front of card
	printf "$FRONT\n"

	# Accept user's answer
	read -r ANSWER < /dev/tty

	# Compare cards
	if [[ $ANSWER == $BACK ]]; then
		printf "✔︎ Correct! ☺︎\n\n"
	else
		printf "✘ Incorrect ☹︎\n"
		printf "$BACK\n\n"
	fi


done < $INPUT





